---
- hosts:
  - timpano
  - acconci

  tasks:
  - name: ensure the scratch directory is there
    file: path=/local/scratch state=directory owner=root group=root mode=777
  - name: ensure the utils directory is there
    file: path=/local/utils state=directory owner=root group=root mode=755
  - name: ensure the admins directory is there
    file: path=/local/admins state=directory owner=root group=root mode=700
  - name: remove utilis directory
    file: path=/local/utilis state=absent
  
  - name: sync utils
    synchronize: src=/root/client/local/utils dest=/local/ delete=yes compress=no
  - name: sync admins
    synchronize: src=/root/client/local/admins dest=/local/ delete=yes compress=no
